### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by ghost** [christ0ph3r/cryptocurrency-cli#9]
Hi,
I have the following issue after start on an arch based manajro system.

`SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/home/USER/Projekte/cryptocurrency-cli/index.js:41:19)
    at Request.self.callback (/home/USER/Projekte/cryptocurrency-cli/node_modules/request/request.js:185:22)
    at Request.emit (node:events:376:20)
    at Request.<anonymous> (/home/USER/Projekte/cryptocurrency-cli/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:376:20)
    at IncomingMessage.<anonymous> (/home/USER/Projekte/cryptocurrency-cli/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:482:28)
    at IncomingMessage.emit (node:events:388:22)
    at endReadableNT (node:internal/streams/readable:1294:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
`

**Comment by testbughub** [comment]
+1

**Comment by piyoki** [comment]
+1

**Comment by pepa65** [comment]
It seems this app is no longer working??

**Comment by pepa65** [comment]
@christ0ph3r Any thought why things are no longer working?

**Comment by 1deadpixl** [comment]
Looks like coinmarketcap.com changed their API and the app needs to be updated.
The endpoint that first gets requested now returns a 410 error (after returning a Cloudflare bot wall which also needs to handled):

```json
{
"code": "410 Gone",
"reason": "We no longer serving this endpoint here"
}
```

I found this tool via the GH search and it looks like it will work great for what I need.
Perhaps someone has the time to investigate the issue and update the API interface?
I'll submit a PR if I get a chance to work on it.

**Comment by salamwaddah** [comment]
@christ0ph3r any plan to update this?

**Comment by Boyquotes** [comment]
Hello all,

You can test this pull request who fix this    

https://github.com/christ0ph3r/cryptocurrency-cli/pull/10    

Or clone my repo directly if you prefer( more simple )    
https://github.com/Boyquotes/cryptocurrency-cli
